package gui;

public enum Pantallas {
    PANTALLA_BIENVENIDA,PANTALLA_PEDIDOS,PANTALLA_QUIERES_SALIR,PANTALLA_HORA_RECOGIDA,PANTALLA_ACERCA_TARJETA, PANTALLA_INTRODUCE_PIN, PANTALLA_RESUMEN_PEDIDO, PANTALLA_MENU_MANANA, PANTALLA_TIMEOUT_INTERACCION
}
